"""검색/동기화에서 허용하는 탤런트 채널 ID 목록."""

ALLOWED_CHANNEL_IDS = {
    "UCp6993wxpyDPHUpavwDFqgg",
    "UCDqI2jOz0weumE8s7paEk6g",
    "UC_hM6YJuNYVAmUWxeIr9FeA",
    "UC5CwaMl1eIgY8h02uZw7u8A",
    "UC0TXe_LYZ4scaW2XMyi5_kw",
    "UCdn5BQ06XqgXoAxIhbqw5Rg",
    "UCQ0UDLQCjY0rmuxCDE38FGg",
    "UCFTLzh12_nrtzqBPsTCqenA",
    "UC1CfXB_kRs3C_zaeTG3oGyg",
    "UC1opHUrw8rvnsadT_iGp7Cg",
    "UCXTpFs_3PqI41qX2d9tL2Rw",
    "UC7fk0CB07ly8oSl0aqKkqFg",
    "UC1suqwovbL1kzsoaZgFZLKg",
    "UCvzGlP9oQwU__Y0r9id_jnA",
    "UCp_5t9SrOQwXMU7iIjQfARg",
    "UCvaTdHTWBGv3MKj3KVqJVCw",
    "UChAnqc_AY5_I3Px5dig3X1Q",
    "UC1DCedRgGHBdm81E1llLhOQ",
    "UCvInZx9h3jC2JzsIzoOebWg",
    "UCdyqAaZDKHXg4Ahi7VENThQ",
    "UCCzUftO8KOVkV4wQG1vkUvg",
    "UCZlDXzGoo7d44bwdNObFacg",
    "UCqm3BQLlJfvkTsX_hvm0UmA",
    "UC1uv2Oq6kNxgATlCiez59hw",
    "UCa9Y57gfeY0Zro_noHRVrnw",
    "UCS9uQI_jC3DE0L4IpXyvr6w",
    "UCFKOVgVbGmX65RxO3EtH3iw",
    "UCAWSyEs_Io8MtpY3m_zqILA",
    "UCUKD_uaobj9jiqB_VXt71mA",
    "UCK9V2B22uJYu3N7eR_BT9QA",
    "UCENwRMx5Yh42zWpzURebzTw",
    "UC6eWCld0KwmyHFbAqK3V_Rw",
    "UCs9_O1tRPMQTHQ_N_L6FU2g",
    "UCIBY1ollUsauvVi4hW4cumw",
    "UC_vMYWcDjmfdpH6r4TTn1MQ",
    "UCWQtYtq9EOB4_I5P_3fh8lA",
    "UCtyWhCj3AqKh2dXctLkDtng",
    "UCdXAk5MpyLD8594lm_OvtGQ",
    "UC1iA6_NT4mtAcIII6ygrvCw",
    "UCMGfV7TVTmHhEErVJg1oHBQ",
    "UC9LSiN9hXI55svYEBrrK_tw",
    "UCuI_opAVX6qbxZY_a_AxFuQ",
    "UCjk2nKmHzgH5Xy_C5qYRd5A",
    "UCKMWFR6lAstLa7Vbf5dH7ig",
    "UCGzTVXqMQHa4AgJVJIVvtDQ",
    "UCL_qhgtOy0dy1Agp8vkySQg",
    "UCHsx4Hqa_1ORjQTh9TYDhww",
    "UCMwGHR0BTZuLsmjY_NT5Pwg",
    "UCoSrY_IQQVpmIRZ9Xf_y93g",
    "UCyl1z3jo3XHR1riLFKG5UAg",
    "UC8rcEBzJSleTkf__agPM20g",
    "UCO_aKKYxn4tvrqPjcTzZ6EQ",
    "UCmbs8T6MWqUHP1tIQvSgKrg",
    "UC3n5uGu18FoCy23ggWWp8tA",
    "UCgmPnx_EEeOrZSg5Tiw7ZRQ",
    "UCgnfPPb9JI3e9A4cXHnWbyg",
    "UC9p_lqQ0FEDz327Vgf5JwqA",
    "UC_sFNM0z0MWm9A6WlKPuMMg",
    "UCt9H_RpQzhxzlyBxFqrdHqA",
    "UCW5uhrG1eCBYditmhL0Ykjw",
    "UCl69AEx4MdqMZH7Jtsm7Tig",
    "UCDHABijvPBnJm7F_KlNME3w",
    "UCvN5h1ShZtc7nly3pezRayg",
    "UCOyYb1c43VlX9rc_lT6NKQw",
    "UCP0BspO_AMEe3aQqqpo89Dg",
    "UCAoy6rzhSf4ydcYjJw3WoVg",
    "UCYz_5n_uDuChHtLo7My1HnQ",
    "UC727SQYUvx5pDDGQpTICNWg",
    "UChgTyjG_pdNvxxhdsXfHQ5Q",
    "UCTvHWSfBZgtxE4sILOaurIQ",
    "UCZLZ8Jjx_RN2CXloOmgTHVg",
    "UCjLEmnpCNeisMxy134KPwWw",
    "UCl_gCybOJRIgOXw6Qb4qJzQ",
    "UCD8HOxPs4Xvsm8H0ZxXGiBw",
    "UCrV1Hf5r8P148idjoSfrGEQ",
    "UCLIpj4TmXviSTNE_U5WG_Ug",
    "UCt30jJgChL8qeT9VPadidSw",
    "UClS3cnIUM9yzsBPQzeyX_8Q",
}


def normalize_channel_id(channel_id):
    return str(channel_id or "").replace("-", "_")


def is_allowed_channel_id(channel_id):
    return normalize_channel_id(channel_id) in ALLOWED_CHANNEL_IDS
